name: docs

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up JDK11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.9'
        java-package: jdk
        architecture: x64
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
    - name: Generate docs
      run: cd telegrindr && mvn javadoc:javadoc && cd ..
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: docs
        folder: telegrindr/target/site/apidocs
        target-folder: docs
